modules:
  direct_links:
    pages: true
    content: true
    documents: true
    links: true
  site_links:
    document_categories: true
    tags: true
    strings: true
    languages: true
    mass_upload: true
  admin_links:
    users:
      requires_right:   is_admin
    groups:
      requires_right:   is_admin
    document_types:
      requires_right:   is_admin
    module_manager:
      requires_right:   is_admin
    info:
      requires_right:   is_admin
    config:
      requires_right:   is_admin
    stats:
      requires_right:   is_admin
    check:
      requires_right:   is_admin
    migration:
      requires_right:   is_admin
    mysql_dump_loader:
      requires_right:   is_admin
    mysql_dump_exporter:
      requires_right:   is_admin

general: 
# logout for frontend or back to login 
  logout_to_login: false