%YAML 1.1
connection:
  phptype:    'mysql'
  hostspec:   'localhost'
  database:   'database'
  username:   'myusername' &un
  user:       *un
  password:   'mypassword'
  dsn:        'mysql:dbname=database;host=localhost'
database:
  adapter:  'mysql'
