admin_menu:
  left:
    - preview
    - edit
    -
      - module.pages
      - module.users
      - ~
      - module.documents
      - module.links
    - module.dashboard
  right:
    - activity
    - domain_name
    - logo
    - user
    - logout

rich_text:
  buttons: [['bold', 'italic', '~'], []]
  