admin_menu:
  left:
    - preview
    - edit
    -
      - module.pages
      - module.documents
      - module.links
      - ~
      - module.users
    - module.dashboard
  right:
    - activity
    - tag
    - domain_name
    - logo
    - user
    - logout

rich_text:
  buttons: [['bold', 'italic', '~'], []]
  
dashboard:
  documents:
    - document_types
    - document_categories
  users:
    - user_groups
    # - user_roles
  