admin_menu:
  left:
    - preview
    - edit
    -
      - module.pages
      - module.documents
      - module.links
      - ~
      - module.users
    - module.dashboard
  right:
    - activity
    - tag
    - domain_name
    - logo
    - user
    - logout

rich_text:
  buttons: [['bold', 'italic', '~'], []]
  
dashboard:
  layout: 3columns
  widgets:
    -
      type: recent_activity
      title: "Recent Activity"
      color: "#554499"
      config:
        days: 3
